version: "3"
services:
  web:
    build: .
    ports:
      - "5000:5000"
    stdin_open: true
    tty: true
    volumes:
      - .:/home/app/
    depends_on:
      - db
  db:
    image: postgres:10
    env_file: .env
    expose:
      - 5432
